# Generated by Django 4.1.7 on 2023-08-23 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custumer_phone_number', models.CharField(max_length=10, unique=True, verbose_name='')),
                ('uuid', models.UUIDField(default=uuid.UUID('9d4c791a-de5d-4075-bfed-7c10c93001d3'))),
                ('phone_otp', models.CharField(max_length=4, verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custumer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
