# Generated by Django 4.1.7 on 2023-08-23 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('otpauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1bab6ad1-d67a-482b-9c23-42c59da27434')),
        ),
    ]
