# Generated by Django 4.1.7 on 2023-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpauth', '0003_alter_custumer_custumer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='uuid',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
